### ISSUE TITLE
Example to connect to hanatrial.ondemand.com

### ISSUE THREAD

**Issue by manu** [SAP/node-hdb#1]
It will be great if there are some instructions in readme section regarding how to connect to hanatrial.ondemand.com account.

**Comment by mokkapatibhanu** [comment]
i am facing a problem while connecting in cmd i have followed the way as shown above but got an error message 
![111](https://cloud.githubusercontent.com/assets/10865270/6059941/8047ddd2-ad5d-11e4-986e-8959641d98d0.PNG)
please suggest me the solution

**Comment by holgerkoser** [comment]
You cannot use the tunnel. It does not work. You need to get your own instance as I have written above.

Regards, Holger

**Comment by sujithphilip** [comment]
Hello

I have a similar issue, have accounts in both hanatrial and neo. Cannot seem to tunnel to either.
May I please ask someone to help me resolve this? Or at least point to the right places?

![tunnel error](https://cloud.githubusercontent.com/assets/17699681/13564887/b449821e-e472-11e5-8e74-653edaba4b86.png)

Thanks in Advance
Sujith

**Comment by i318136** [comment]
Hi Sujith,

I believe my answer is a bit late but can useful for others who are facing with the same problem. You shouldn't set proxy on command prompt to open a db tunnel.

Regards,
Patrik

**Comment by josehm** [comment]
Hi!
Somebody know if I can use this package in a virtual machine on sap hana neo environment, without tunnel?
Thanks.
