### ISSUE TITLE
Connection timeout when connecting to SYSTEMDB of an MDC HANA

### ISSUE THREAD

**Issue by phil-mitchell** [SAP/node-hdb#108]
This appears to be a regression in 0.15.0.  It works okay in 0.14.0.

Using these credentials, the connection hangs and never completes:
{
    databaseName: 'SYSTEMDB',
    instanceNumber: 90,
    host: 'myhost',
    user: 'SYSTEM',
    password: 'mypass'
}

It works well if I provide port 39013 instead of databaseName + instanceNumber

**Comment by alexpenev-s** [comment]
Please try with version 0.15.1

**Comment by phil-mitchell** [comment]
Confirmed.  Thanks!
