### ISSUE TITLE
Spatial error on batched upserts

### ISSUE THREAD

**Issue by aktivalux** [SAP/node-hdb#111]
Hi,

I am using the batching mechanism to upsert new rows in a table. Sometimes I do get the following error:
```
code:669
level:1
message:"spatial error: exception 1600402: Unexpected end of WKB at position 13. Trying to read 8 bytes, but 3 bytes left only\n at function st_point() (at pos 390) "
position:0
sqlState:"HY000"
```

So far the error only occured when I sent ~1k or more rows in a single batch but not when e.g. sending them in batches of 100 (or maybe this was just luck). The parameters for the spatial columns are passed to node-hdb as Buffer instance. The buffer is created using wkx and the toWkb()-method (and actually I tried to convert the point to Wkb myself but this did not fix the issue).

In order to check if the Wkb are indeed errornous I checked them by executing e.g.
```
SELECT NEW ST_Point('0101000000cb4a9352d0e55c4094d920938c2c3640', 4326) FROM DUMMY
```
The statement executed successfully for all WKBs in the batch that failed (find the full list of WKB/points) attached below.

The table is as follows (cds definition):
```
namespace com.test
context ais {
    entity AIS {
        key MMSI:           BinaryFloat;
        key Time:	    UTCTimestamp;
        GeoPosition:        hana.ST_GEOMETRY(4326);
        GeoPositionPlanar:  hana.ST_GEOMETRY(1000004326);
   }
}
```

The query:
```
var insertQuery = `
   UPSERT
   "${hanaCredentials.schema}"."com.test::ais.AIS"
   ("MMSI", "Time", "GeoPosition", "GeoPositionPlanar") 
   VALUES (?,?,NEW ST_POINT(?, 4326),NEW ST_POINT(?, 4326).ST_Transform(1000004326))
   WHERE "MMSI" = ? AND "Time" = ?;
`
```

The inserted GeoPositions: [wkx_data.txt](https://github.com/SAP/node-hdb/files/1571025/wkx_data.txt)

**Comment by alexpenev-s** [comment]
Hi,
Could you please create a small app that reproduces the issue. I tried to do batch inserts, but couldn't reproduce the issue here.

**Comment by aktivalux** [comment]
Will try to do so but this will take some time

**Comment by alexpenev-s** [comment]
Please reopen if the issue still persists.
