### ISSUE TITLE
crash in Connection socket onerror

### ISSUE THREAD

**Issue by phil-mitchell** [SAP/node-hdb#116]
TypeError: Cannot read property 'receive' of undefined
at Socket.onerror (/home/vcap/app/node_modules/hdb/lib/protocol/Connection.js:229:25)
at Socket.emit (events.js:188:7)
at emitErrorNT (net.js:1281:8)
at _combinedTickCallback (internal/process/next_tick.js:80:11)

I don't know how we got here.  Looking at the code I don't understand how we could possibly get here.  The issue has happened twice in the cloud in the past day or so.

**Comment by bill-frier-sap** [comment]
The problem is currently happening several times per hour. This has become urgent.

**Comment by phil-mitchell** [comment]
Right before the crash, the following error message is received:

> No initialization reply received within 5 sec

I think this is from here:

`timeoutObject = setTimeout(onerror, self.initializationTimeout, initializationTimeoutError());
`
