### ISSUE TITLE
Can node-hdb APIs be executed synchronously?

### ISSUE THREAD

**Issue by abhikco** [SAP/node-hdb#12]
Hi Holger,
Do you provide a way in which node-hdb database operations can be executed in synchronous fashion conditionally?
The requirements stems from the fact that I would like to execute a few database operations, reacting to the process SIGKILL event. According to node.js process docs, the event handler must only execute synchronous stuff for any guarantee for execution.

Best Regards,
Abhi

**Comment by holgerkoser** [comment]
There is no synchronous API for node-hdb and I will not add a one. If you really need a synchronous API 
you may use something like [node-fibers](https://github.com/laverdet/node-fibers).
