### ISSUE TITLE
How to pass clientId?

### ISSUE THREAD

**Issue by rena08** [SAP/node-hdb#124]
Hello, I need to pass the clientId to the server and I don't know how to do it.

For example the clientId '300'.

Thank you.

**Comment by alexpenev-s** [comment]
Hi, You should be be able to pass 'ClientId' to the connection options. 
If it doesn't work with the current version could you please try with: 
https://github.com/SAP/node-hdb/tree/cl

**Comment by rena08** [comment]
Thank you for your response. I am trying to execute this code:

`var hdb    = require('hdb');
var client = hdb.createClient({
  host     :  192.168.144.10,
  port     :   10101,
  user     : 'user',
  instanceNumber : '00',
  password: 'password',
  ClientId: '300',
});

client.on('error', function (err) {
    console.log(client.readyState);
    console.error('Network connection error', err);
});

client.connect(function (err) {
    if (err) return console.error('Connect error', err);

    console.log(client.readyState);
    console.log('Se ha conectado con éxito');
});`

Is this correct? Because I get the error "Could not connect to any host: [ 192.168.144.12:10101 - read ECONNRESET" and I don't know if the error is on the client or on the server.

Thanks in advance!

**Comment by alexpenev-s** [comment]
Sorry I made a typo. It should be 'clientId'.
The port looks wrong, check with HANA what is the correct one it should begin with 3....
Example: 30015

**Comment by rena08** [comment]
Sorry but in the example I put samples values. In my case the port does begin with 3, specifically 3300.

I still can't connect with 'clientId'

Thank you.

**Comment by alexpenev-s** [comment]
If you don't add the 'clientId' property can you log in?
Maybe check the logs file of HANA - it there is information on why the connection is dropped.

**Comment by alexpenev-s** [comment]
Also try adding the env variable
NODE_DEBUG=hdb
you should see a lot of debug info - hopefully something useful is in there.

**Comment by rena08** [comment]
I remove the 'clientId' property but I can't log in. I am going to see the logs files of HANA and may be there are the solution.

Thanks in advance!

**Comment by rena08** [comment]
Hello,

I was looking the logs in HANA server and I have found this:

![sap](https://user-images.githubusercontent.com/17997480/36794551-66e19556-1c7f-11e8-9585-d0f5d6e6d556.png)

I found the error (reason 7) and that says " Invalid user type ". I sent the type 'a' and I need to send the type 'c' (comunication user).

Are this related to SAP user or the library?

Thanks in advance!

**Comment by alexpenev-s** [comment]
Hi,
I am not sure. All I can find is this SAP note: https://launchpad.support.sap.com/#/notes/320991

**Comment by alexpenev-s** [comment]
Hi,
Were you able to resolve the issue?

**Comment by rena08** [comment]
Hello,

I could not pass the clientId. I had to change the programming language.

**Comment by alexpenev-s** [comment]
I going to close this issue for now. It seems that there were unknown problems establishing a connection, so we never got to passing a clientId.
