### ISSUE TITLE
No initialization reply received within 5 sec

### ISSUE THREAD

**Issue by kateflower** [SAP/node-hdb#126]
Hi,

I have this problem that when the database is under load, the HDB client will not connect to the database, and will terminate existing connections.  The driver continues to fire off the following error:

No initialization reply received within 5 sec

The database is not dead, you can connect with Hana Studio (eclipse), but it is under load (cpu around 80%).

It's kind of bothersome because it is causing my applications to fail. 

Does anyone know what is causing this issue and how I could avoid it - except for not running anything on the database :-)

A 5 second timeout is kind of short.

**Comment by alexpenev-s** [comment]
Hi,
You could change the timeout by passing the option ex. initializationTimeout:150000 to the createClient call as part of the options.
This should increase the timeout.

**Comment by kateflower** [comment]
Thanks that did the trick.
