### ISSUE TITLE
Date format changed with l @sap/hana-client

### ISSUE THREAD

**Issue by kateflower** [SAP/node-hdb#128]
Hi,

After switching over to @sap/hana-client we have noticed that the date format has changed. 

select current_utctimestamp from dummy;

old format:

[ { CURRENT_UTCTIMESTAMP: '2018-03-19T15:23:21.304' } ]

new format:

[ { CURRENT_UTCTIMESTAMP: '2018-03-19 15:17:10.446000000' } ]

Which ends up breaking our frontend application. Anyway for me to get the old format back?

Thanks.

**Comment by alexpenev-s** [comment]
Hi, It looks like the behaviour of the new driver is consistent with the HANA timestamp format. https://help.sap.com/viewer/4fe29514fd584807ac9f2a04f6754767/2.0.02/en-US/3f81ccc7e35d44cbbc595c7d552c202a.html I am not sure they would be willing to change that behaviour. 
Is it an option to do the conversion manually after fetching the date  ex. (new Date('2018-03-19 15:17:10.446000000')).toISOString()

Another option is  to use to_varchar to format the output ex. select to_varchar(current_utctimestamp,'YYYY-MM-DD HH:SS.FF3') from dummy

**Comment by kateflower** [comment]
Thanks for the examples.
Looks like I am just going to have to deal with the change.  Many Thanks.
K.
