### ISSUE TITLE
Out Parameter defined as NUMBER is returned as a JS string

### ISSUE THREAD

**Issue by abhikco** [SAP/node-hdb#13]
Hi,
I have a stored procedure with the following structure:

PROCEDURE "SCHEMA_NAME"."UPDATE_ME" ( IN ID NUMBER, OUT NUM_JOBS NUMBER, OUT SCHEDULES_TAB "SCHEMA_NAME"."MY_TYPE")

Upon executing the procedure using node-hdb, the scalar OUT parameter "NUM_JOBS" is returned as a string with a value similar to "0e+0". In JS code, this effectively rules out using strict equals operators to compare values (e.g. "0e+0" === 0 returns false).
Is this intended behaviour? Shouldn't the API return scalars by automatically converting the type to JS type?

Best Regards
Abhi

**Comment by holgerkoser** [comment]
The database type NUMBER results in a decimal and the value range of the decimal is much larger than the javascript number data type. Therefore this kind of decimals are always returned as strings in order to avoid loss of precision errors. So it is the intended behaviour.
