### ISSUE TITLE
New `hana-client` is missing a public repository

### ISSUE THREAD

**Issue by rlindner81** [SAP/node-hdb#130]
Why would you switch from a driver with a public repository and transparent versioning to one without?

Not only does the repo not exist, if you actually install the package as the documentation suggests, the info that is part of the npm metadata points to a non-existing repository:

```
npm view @sap/hana-client
...
  repository: { url: 'git+https://github.com/hana/node-hana.git' },
  bugs: { url: 'https://github.com/hana/node-hana/issues' },
  homepage: 'https://github.com/hana/node-hana#readme',
```
But the https://github.com/hana account is not associated in any way with HANA or SAP.

**Comment by alexpenev-s** [comment]
At the moment the other driver has more active development and has new features that we haven't had time to add here.

**Comment by privateOmega** [comment]
@alexpenev-s Could you please post the new package naem as I am unable to find `@sap/hana-client` and the `npm install` command fails.?

**Comment by alexpenev-s** [comment]
> @alexpenev-s Could you please post the new package naem as I am unable to find `@sap/hana-client` and the `npm install` command fails.?

The package is available through sap's npm registry. See https://help.sap.com/viewer/4505d0bdaf4948449b7f7379d24d0f0d/2.0.03/en-US/726e5d41462c4eb29eaa6cc83ff41e84.html

**Comment by privateOmega** [comment]
This is what I get when I try to follow those steps.
```
> npm config set @sap:registry https://npm.sap.com

> npm install @sap/hana-client                                                                                                                                                                                                               npm ERR! code E404
npm ERR! 404 Not Found: @sap/hana-client@latest
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<user>\AppData\Roaming\npm-cache\_logs\2019-08-01T10_14_47_460Z-debug.log
```

**Comment by krynv** [comment]
> This is what I get when I try to follow those steps.
> 
> ```
> > npm config set @sap:registry https://npm.sap.com
> 
> > npm install @sap/hana-client                                                                                                                                                                                                               npm ERR! code E404
> npm ERR! 404 Not Found: @sap/hana-client@latest
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\<user>\AppData\Roaming\npm-cache\_logs\2019-08-01T10_14_47_460Z-debug.log
> ```

Create an `.npmrc` file in your project root.
Add `@sap:registry=https://npm.sap.com` to the file.
Run the `npm install @sap/hana-client` command.
