### ISSUE TITLE
spelling error in error message

### ISSUE THREAD

**Issue by I817563** [SAP/node-hdb#138]
Typo in ExecuteTask.js
return cb(new Error('Cannon set parameter at row: ' + row + '. ' + err.message));
should be Cannot set Parameter at row....

**Comment by alexpenev-s** [comment]
Good catch

**Comment by alexpenev-s** [comment]
Looks like it's already fixed: https://github.com/SAP/node-hdb/commit/acbe4f75f39f4d58ba0ddf8d8651f3776b89b565
