### ISSUE TITLE
ECONNRESET Error

### ISSUE THREAD

**Issue by kurzy** [SAP/node-hdb#14]
I am getting an unhandled error event when the connection to the HANA gets lost, e.g., because of restarting it.:
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:550:26)
```
Is it possible to catch it within the node-hdb module?

**Comment by holgerkoser** [comment]
Network connection errors must be handled by the application. You will have to register an error event handler for this kind of problem. 

```js
var hdb    = require('hdb');
var client = hdb.createClient({
  host     : 'hostname',
  port     : 30015,
  user     : 'user',
  password : 'secret'
});
client.on('error', function (err) {
  console.error('Network connection error', err);
});
console.log(client.readyState); // new
```

I will add this to the README because it is currently not mentioned explicitly.
