### ISSUE TITLE
New hana-client error whilst installing inside docker

### ISSUE THREAD

**Issue by dedicad** [SAP/node-hdb#148]
# Question about Hana-client inside Docker

You're suggesting switching to @sap/hana-client, so I switched to that lib. 

 ---

Packages installation is perfectly working on my computer with 
`npm config set @sap:registry https://npm.sap.com`

However inside a docker container I have the following Fatal error occuring during install :
`Failed to load DBCAPI.` during node checkbuild.js

Full Stack trace : 
```
FATAL ERROR: A fatal error occurred during install.
Failed to load DBCAPI.
    at ProcessTermError.ExtendableBuiltin (/opt/yarn-v1.13.0/lib/cli.js:727:66)
    at ProcessTermError.MessageError (/opt/yarn-v1.13.0/lib/cli.js:756:123)
    at new ProcessTermError (/opt/yarn-v1.13.0/lib/cli.js:796:113)
    at ChildProcess.<anonymous> (/opt/yarn-v1.13.0/lib/cli.js:25795:17)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

error /usr/src/app/node_modules/@sap/hana-client: Command failed.
Exit code: 255
Command: node checkbuild.js
Arguments: 
Directory: /usr/src/app/node_modules/@sap/hana-client
Output:
FATAL ERROR: A fatal error occurred during install.
Failed to load DBCAPI.
```
---

Maybe docker container is missing some rights or some configuration that my computer has ?

I am a little new to this and I did not find any solution online. Since new repository is private, I am trying to search some solution here.

Thank you for reading this issue.

**Comment by BenoitRanque** [comment]
Hello
I'm having this exact issue, did you solve it?
I've found [this](https://github.com/entmike/hana-sql-sandbox-docker) repo that has what looks to be a working example, they seem to be installing a python driver so maybe that is a requirement?
I'll be trying out something today, will post any findings here

**Comment by BenoitRanque** [comment]
Update: I've managed to get this to work. Before using installing `@sap/hana-client` you must install the python drivers with `pip install hdbcli`

**Comment by dedicad** [comment]
Thank you ! The working solutions I had found was to change from a light node image (node-alpine) to a normal one in my docker container. 
This could be because the light one doesn't have the python driver you talked about, pre-installed.

**Comment by BenoitRanque** [comment]
No thank You! Your comment prompted my to try something else: moved from node alpine to node slim. Worked a charm! Turns out you don't need the python lib!

**Comment by alumni** [comment]
Is there a repo URL for @sap/hana-client? Issues for it should be reported there (I would like to report one too, but I don't know where - typical @SAP 😆)

**Comment by DanCummins-SAP** [comment]
Hi all, I thought I would leave one more comment on why you might get "Failed to load DBCAPI".  dbcapi is a C-Api DLL/Shared object that the native code tries to load at startup.  DBCAPI is glibc-based, so it is possible if you use a musl-based docker container, it would not load.
Dan

**Comment by SrimukhaKarantha** [comment]
I was facing the same issue, but in my case it was in my normal local setup in windows. The issue got fixed after I downloaded and installed the the python version for Win32(even though my system was 64 bit). It somehow doesn't work with python 64 bit.
