### ISSUE TITLE
New package @sap/hana-client not working since last release (April 20)

### ISSUE THREAD

**Issue by dedicad** [SAP/node-hdb#152]
I switched to the new hana-client a few weeks ago. It was working perfectly but for 2 days now I am unable to download it again and my npm installs are failing because of it.

## Reproduce
Just try :
- `npm config set @sap:registry https://npm.sap.com`
- `npm install @sap/hana-client`

I also link to this comment :

_

> it would be nice to have a place to put issues about the new plugin : 
> Is there a repo URL for @sap/hana-client? Issues for it should be reported there (I would like to report one too, but I don't know where - typical @SAP 😆)

_

_Originally posted by @alumni in https://github.com/SAP/node-hdb/issues/148#issuecomment-617089454_

**Comment by alumni** [comment]
If you are an @SAP employee, there are some repos for hana-client in the enterprise github. I had to dig deep, but managed to find the right one (got lucky that a new version was released recently so it showed at the top).

**Comment by DanCummins-SAP** [comment]
Hi dedicad, 

We recently started posting to npmjs.com, see:  https://www.npmjs.com/package/@sap/hana-client

So you should be able to get the latest public version there, with no special repository setting needed.

Dan

**Comment by dedicad** [comment]
Thank you so much for you answers, I am not an SAP employee but my company is using Hana Database. 
Removing the npm config and use the public repository has worked for me.
