### ISSUE TITLE
[@sap/hana-client] Support NodeJS v14.X 

### ISSUE THREAD

**Issue by nenov92** [SAP/node-hdb#164]
Hi colleagues,

Is there a plan **hana-client** to support NodeJS v14.X. Soon version 12.X is going out of LTS and 14.X as of now is the new LTS version?

Reference: https://nodejs.org/en/about/releases/

Best regards,
Miroslav

**Comment by jeffalbion** [comment]
Hello,

The latest 2.7.16 @sap/hana-client release now supports node.js versions 8 and higher.

Best regards,
Jeff
