### ISSUE TITLE
Connect with Hana as a Service fails

### ISSUE THREAD

**Issue by parthjhalani** [SAP/node-hdb#165]
Hi,

I have HAAS instance running in CF. Using HDB i am not able to connect with the instance. 
I am using hostname of db with port 443, and  getting error as 'could not connect to any host no responses received before x seconds'. I  have tried to increase timeout as well using initializationTimeout which didn't help.

I am able to use hana-client and connect but because the package size of hana-client is too large i prefer to use hdb.

**Comment by parthjhalani** [comment]
0: Connect error
1: Error: Could not connect to any host: [ f3ca5991-878d-47ec-b2cc-79fe8446ce87.hana.prod-eu10.hanacloud.ondemand.com:443 - No initialization reply received within 15 sec ]
[[StableObjectId]]: 1
code: "EHDBOPENCONN"
message: "Could not connect to any host: [ f3ca5991-878d-47ec-b2cc-79fe8446ce87.hana.prod-eu10.hanacloud.ondemand.com:443 - No initialization reply received within 15 sec ]"
stack: "Error: Could not connect to any host: [ f3ca5991-878d-47ec-b2cc-79fe8446ce87.hana.prod-eu10.hanacloud.ondemand.com:443 - No initialization reply received within 15 sec ] at couldNotOpenConnectionError (/home/user/projects/uxtools-db/node_modules/hdb/lib/protocol/ConnectionManager.js:115:13) at tryConnect (/home/user/projects/uxtools-db/node_modules/hdb/lib/protocol/ConnectionManager.js:35:17) at /home/user/projects/uxtools-db/node_modules/hdb/lib/protocol/ConnectionManager.js:42:9 at handleError (/home/user/projects/uxtools-db/node_modules/hdb/lib/protocol/ConnectionManager.js:74:5) at /home/user/projects/uxtools-db/node_modules/hdb/lib/protocol/ConnectionManager.js:79:14 at Timeout.onerror (/home/user/projects/uxtools-db/node_modules/hdb/lib/protocol/Connection.js:175:5) at ontimeout (timers.js:438:13) at tryOnTimeout (timers.js:300:5) at listOnTimeout (timers.js:263:5) at Timer.processTimers (timers.js:223:10)"
__proto__: Object {constructor: , name: "Error", message: "", …}

**Comment by parthjhalani** [comment]
0: Connect error
1: Error: Could not connect to any host: [ *.hana.prod-eu10.hanacloud.ondemand.com:443 - No initialization reply received within 15 sec ]
[[StableObjectId]]: 1
code: "EHDBOPENCONN"
message: "Could not connect to any host: [ *.hana.prod-eu10.hanacloud.ondemand.com:443 - No initialization reply received within 15 sec ]"
stack: "Error: Could not connect to any host: [ *.hana.prod-eu10.hanacloud.ondemand.com:443 - No initialization reply received within 15 sec ] at couldNotOpenConnectionError (/home/user/projects/uxtools-db/node_modules/hdb/lib/protocol/ConnectionManager.js:115:13) at tryConnect (/home/user/projects/uxtools-db/node_modules/hdb/lib/protocol/ConnectionManager.js:35:17) at /home/user/projects/uxtools-db/node_modules/hdb/lib/protocol/ConnectionManager.js:42:9 at handleError (/home/user/projects/uxtools-db/node_modules/hdb/lib/protocol/ConnectionManager.js:74:5) at /home/user/projects/uxtools-db/node_modules/hdb/lib/protocol/ConnectionManager.js:79:14 at Timeout.onerror (/home/user/projects/uxtools-db/node_modules/hdb/lib/protocol/Connection.js:175:5) at ontimeout (timers.js:438:13) at tryOnTimeout (timers.js:300:5) at listOnTimeout (timers.js:263:5) at Timer.processTimers (timers.js:223:10)"
__proto__: Object {constructor: , name: "Error", message: "", …}

**Comment by larshp** [comment]
try setting `useTLS   : true,` in the connection options
