### ISSUE TITLE
Closing a connection twice causes an error

### ISSUE THREAD

**Issue by friegger** [SAP/node-hdb#17]
When closing a client connection twice it gives the following error in [lib/protocol/Connection.js#L475](https://github.com/SAP/node-hdb/blob/master/lib/protocol/Connection.js#L475):
```javascript
  if (this._queue.empty && !this._queue.busy) {
                 ^
TypeError: Cannot read property 'empty' of undefined
```

While closing it twice doesn't make a lot of sense, this can be made more robust. A second close should just be a noop. It also would remove the burden from the user to check for the connection state before closing. What do you think?

**Comment by holgerkoser** [comment]
I will ignore close close of connection if already closed in the next version.
