### ISSUE TITLE
Reconnection of client after Network connection error results in error on Statement Execution

### ISSUE THREAD

**Issue by LeoKotschenreuther** [SAP/node-hdb#18]
After an Error in the Client Object the Client seems to get closed.
As we have the option 'autoReconnect' enabled, it reconnects to Hana again.
See the messages in the terminal, the functions onerror, onclose and onconnect are the same as in [examples/client.js](https://github.com/SAP/node-hdb/blob/master/examples/client.js):

```
Network connection error { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
Client closed
Client connected
```

When we then try to execute a statement, we get the following error in [lib/protocol/Connection.js#L316](https://github.com/SAP/node-hdb/blob/master/lib/protocol/Connection.js#L316)

```
      queueable = this._queue.createTask(this.send.bind(this, task), cb);

TypeError: Cannot call method 'createTask' of undefined
```

**Comment by atejada** [comment]
I can confirm the same...even when I close the connection this error pops out...is there any plan to fix it?

**Comment by holgerkoser** [comment]
I will ignore the `autoReconnect` option in the next version `0.5.x`. I think it makes more sense to use an existing module like [reconnect-core](https://www.npmjs.com/package/reconnect-core) and provide an implementation for this than rebuilding this inside `hdb`. If you use a connection pool you also do not need this kind of feature.

**Comment by holgerkoser** [comment]
I have removed the `autoReconnect` feature in the latest version [`0.5.0`](https://github.com/SAP/node-hdb/releases/tag/v0.5.0). The old behaviour can be implemented as follows:
```js
  client.on('close', function onclose(hadError) {
    if (hadError) {
      this.connect();
    }
  });
```
I have adapted the example [app8](https://github.com/SAP/node-hdb/blob/master/examples/app8.js#L35-L39).
