### ISSUE TITLE
Connection parameters?

### ISSUE THREAD

**Issue by bsrdjan** [SAP/node-hdb#186]
I am trying to connect to this database
![image002](https://user-images.githubusercontent.com/1697847/136386600-f55c39d5-d883-41be-8a98-8ef6f3d9af37.jpg)

using these parameters:

```json
  host: "https://7d71db6e-f279-4afa-9b6e-ce38f2d0fad6.hana.prod-eu10.hanacloud.ondemand.com",
  port: 443,
  instanceNumber: "7d71db6e-f279-4afa-9b6e-ce38f2d0fad6",
  databaseName: "VEH",
  user: "<secret>",
  pwd: "<secret>",
  ```
  
and getting timeout error:
  
```shell
Connect error Error: Could not connect to any host: [ https://7d71db6e-f279-4afa-9b6e-ce38f2d0fad6.hana.prod-eu10.hanacloud.ondemand.com:443 - No initialization reply received within 5 sec ]  
```

Where can I find correct parameters to connect using node-hdb?

**Comment by jonashaus** [comment]
Can you maybe share how you solved this? I'm facing the same issue...
