### ISSUE TITLE
Installation issue with npm install -g @sap/hana-client

### ISSUE THREAD

**Issue by StefanButscher** [SAP/node-hdb#188]
Dear colleagues,

when I try to install via "npm install @sap/hana-client" 

I get the follwoing error:
PS C:\Users\XXXXXX\OneDrive - SAP SE\Agile\Hana@VScode> npm install -g @sap/hana-client

@sap/hana-client@2.10.20 install C:\Users\XXXXX\AppData\Roaming\npm\node_modules@sap\hana-client
node checkbuild.js

npm ERR! code ELIFECYCLE
npm ERR! errno 3221226356
npm ERR! @sap/hana-client@2.10.20 install: node checkbuild.js
npm ERR! Exit status 3221226356
npm ERR!
npm ERR! Failed at the @sap/hana-client@2.10.20 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\XXXXX\AppData\Roaming\npm-cache_logs\2021-11-15T07_23_32_052Z-debug.log
PS C:\Users\XXXXXX\OneDrive - SAP SE\Agile\Hana@VScode>

I am completely lost what needs to be done to overcome this.

Thanks and Best Regards,
Stefan

**Comment by jeffalbion** [comment]
Hi Stefan,

This area of support is for the hdb driver. If you have issues with the @sap/hana-client, you should open a question on answers.sap.com with the tag 'HANA'. If you have a support contract, you should open an SAP Support Case underneath the 'HAN-DB-CLI' component.

To answer your question, I think we'll need some more information: which version of node.js are you using? The driver should be supported on node.js major versions 8 and up.

Does the debug.log file provide any further details?

Best regards,
Jeff

**Comment by StefanButscher** [comment]
Dear Jeff,

thanks for the Info. I am an SAP employee and could of course open a ticket. 
Initially I opened the finding on the sap-han-driver-for-sql-tools, but got redirected to here.
https://github.com/SAP/sap-hana-driver-for-sqltools/issues/202

From the debug.log the Versions are:
node v14.16.1
npm  v6.14.12

From the debug.log I cannot see any further issues. I will add the latest file in a new comment and (removed my user ID).

Thanks and Best Regards,
Stefan

**Comment by StefanButscher** [comment]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '@sap/hana-client'
1 verbose cli ]
2 info using npm@6.14.12
3 info using node@v14.16.1
4 verbose npm-session c5a26ee74aecdd24
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 http://nexus.wdf.sap.corp:8081/nexus/content/groups/build.milestones.npm/@sap%2fhana-client 19ms (from cache)
8 silly pacote tag manifest for @sap/hana-client@latest fetched in 44ms
9 timing stage:loadCurrentTree Completed in 71ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 0ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule @sap/hana-client@2.12.1-ms checking installable status
17 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 7ms
18 timing stage:loadIdealTree Completed in 11ms
19 silly currentTree Data
20 silly idealTree Data
20 silly idealTree `-- @sap/hana-client@2.12.1-ms
20 silly idealTree   +-- debug@3.1.0
20 silly idealTree   `-- ms@2.0.0
21 silly install generateActionsToTake
22 timing stage:generateActionsToTake Completed in 4ms
23 silly diffTrees action count 3
24 silly diffTrees add ms@2.0.0
25 silly diffTrees add debug@3.1.0
26 silly diffTrees add @sap/hana-client@2.12.1-ms
27 silly decomposeActions action count 24
28 silly decomposeActions fetch ms@2.0.0
29 silly decomposeActions extract ms@2.0.0
30 silly decomposeActions preinstall ms@2.0.0
31 silly decomposeActions build ms@2.0.0
32 silly decomposeActions install ms@2.0.0
33 silly decomposeActions postinstall ms@2.0.0
34 silly decomposeActions finalize ms@2.0.0
35 silly decomposeActions refresh-package-json ms@2.0.0
36 silly decomposeActions fetch debug@3.1.0
37 silly decomposeActions extract debug@3.1.0
38 silly decomposeActions preinstall debug@3.1.0
39 silly decomposeActions build debug@3.1.0
40 silly decomposeActions install debug@3.1.0
41 silly decomposeActions postinstall debug@3.1.0
42 silly decomposeActions finalize debug@3.1.0
43 silly decomposeActions refresh-package-json debug@3.1.0
44 silly decomposeActions fetch @sap/hana-client@2.12.1-ms
45 silly decomposeActions extract @sap/hana-client@2.12.1-ms
46 silly decomposeActions preinstall @sap/hana-client@2.12.1-ms
47 silly decomposeActions build @sap/hana-client@2.12.1-ms
48 silly decomposeActions install @sap/hana-client@2.12.1-ms
49 silly decomposeActions postinstall @sap/hana-client@2.12.1-ms
50 silly decomposeActions finalize @sap/hana-client@2.12.1-ms
51 silly decomposeActions refresh-package-json @sap/hana-client@2.12.1-ms
52 silly install executeActions
53 silly doSerial global-install 24
54 verbose correctMkdir C:\Users\<user>\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
55 verbose makeCacheDir UID & GID are irrelevant on win32
56 verbose lock using C:\Users\<user>\AppData\Roaming\npm-cache\_locks\staging-accbe1e340b579ac.lock for C:\Users\<user>\AppData\Local\vscode-sqltools\Data\node_modules\.staging
57 silly doParallel extract 3
58 silly extract @sap/hana-client@2.12.1-ms
59 silly extract ms@2.0.0
60 silly extract debug@3.1.0
61 silly tarball trying ms@2.0.0 by hash: sha1-VgiurfwAvmwpAd9fmGF4jeDVl8g=
62 silly tarball trying @sap/hana-client@latest by hash: sha512-CNh5RIYNTyMH5PPsPq6t8nca73QxXoCxGFjfKKvhRlaGJsLq9jpD9YmDk2FYKEGyMGzFOdNKuB+zOuJcBgnT7g==
63 silly tarball trying debug@3.1.0 by hash: sha512-OX8XqP7/1a9cqkxYw2yXss15f26NKWBpDXQd0/uK/KPqdQhxbPa994hnzjcE2VqQpDslf55723cKPUOGSmMY3g==
64 silly extract ms@2.0.0 extracted to C:\Users\<user>\AppData\Local\vscode-sqltools\Data\node_modules\.staging\ms-5d8d6213 (42ms)
65 http fetch POST 404 http://nexus.wdf.sap.corp:8081/nexus/content/groups/build.milestones.npm/-/npm/v1/security/audits/quick 82ms
66 silly extract debug@3.1.0 extracted to C:\Users\<user>\AppData\Local\vscode-sqltools\Data\node_modules\.staging\debug-f5163411 (54ms)
67 silly extract @sap/hana-client@latest extracted to C:\Users\<user>\AppData\Local\vscode-sqltools\Data\node_modules\.staging\@sap\hana-client-11f6d6fd (1654ms)
68 timing action:extract Completed in 1658ms
69 silly doReverseSerial unbuild 24
70 silly doSerial remove 24
71 silly doSerial move 24
72 silly doSerial finalize 24
73 silly finalize C:\Users\<user>\AppData\Local\vscode-sqltools\Data\node_modules\@sap\hana-client\node_modules\ms
74 silly finalize C:\Users\<user>\AppData\Local\vscode-sqltools\Data\node_modules\@sap\hana-client\node_modules\debug
75 silly finalize C:\Users\<user>\AppData\Local\vscode-sqltools\Data\node_modules\@sap\hana-client
76 timing action:finalize Completed in 49ms
77 silly doParallel refresh-package-json 3
78 silly refresh-package-json C:\Users\<user>\AppData\Local\vscode-sqltools\Data\node_modules\@sap\hana-client\node_modules\ms
79 silly refresh-package-json C:\Users\<user>\AppData\Local\vscode-sqltools\Data\node_modules\@sap\hana-client\node_modules\debug
80 silly refresh-package-json C:\Users\<user>\AppData\Local\vscode-sqltools\Data\node_modules\@sap\hana-client
81 timing action:refresh-package-json Completed in 25ms
82 silly doParallel preinstall 3
83 silly preinstall ms@2.0.0
84 info lifecycle ms@2.0.0~preinstall: ms@2.0.0
85 silly preinstall debug@3.1.0
86 info lifecycle debug@3.1.0~preinstall: debug@3.1.0
87 silly preinstall @sap/hana-client@2.12.1-ms
88 info lifecycle @sap/hana-client@2.12.1-ms~preinstall: @sap/hana-client@2.12.1-ms
89 timing action:preinstall Completed in 1ms
90 silly doSerial build 24
91 silly build ms@2.0.0
92 info linkStuff ms@2.0.0
93 silly linkStuff ms@2.0.0 has C:\Users\<user>\AppData\Local\vscode-sqltools\Data\node_modules\@sap\hana-client\node_modules as its parent node_modules
94 silly build debug@3.1.0
95 info linkStuff debug@3.1.0
96 silly linkStuff debug@3.1.0 has C:\Users\<user>\AppData\Local\vscode-sqltools\Data\node_modules\@sap\hana-client\node_modules as its parent node_modules
97 silly build @sap/hana-client@2.12.1-ms
98 info linkStuff @sap/hana-client@2.12.1-ms
99 silly linkStuff @sap/hana-client@2.12.1-ms has C:\Users\<user>\AppData\Local\vscode-sqltools\Data\node_modules as its parent node_modules
100 timing action:build Completed in 2ms
101 silly doSerial global-link 24
102 silly doParallel update-linked 0
103 silly doSerial install 24
104 silly install ms@2.0.0
105 info lifecycle ms@2.0.0~install: ms@2.0.0
106 silly install debug@3.1.0
107 info lifecycle debug@3.1.0~install: debug@3.1.0
108 silly install @sap/hana-client@2.12.1-ms
109 info lifecycle @sap/hana-client@2.12.1-ms~install: @sap/hana-client@2.12.1-ms
110 verbose lifecycle @sap/hana-client@2.12.1-ms~install: unsafe-perm in lifecycle true
111 verbose lifecycle @sap/hana-client@2.12.1-ms~install: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\<user>\AppData\Local\vscode-sqltools\Data\node_modules\@sap\hana-client\node_modules\.bin;C:\Users\<user>\AppData\Local\vscode-sqltools\Data\node_modules\.bin;C:\Program Files\SapMachine\JDK\11\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\OpenText\Viewer\bin;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\<user>\AppData\Local\Microsoft\WindowsApps;;C:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\<user>\AppData\Roaming\npm
112 verbose lifecycle @sap/hana-client@2.12.1-ms~install: CWD: C:\Users\<user>\AppData\Local\vscode-sqltools\Data\node_modules\@sap\hana-client
113 silly lifecycle @sap/hana-client@2.12.1-ms~install: Args: [ '/d /s /c', 'node checkbuild.js' ]
114 silly lifecycle @sap/hana-client@2.12.1-ms~install: Returned: code: 3221226356  signal: null
115 info lifecycle @sap/hana-client@2.12.1-ms~install: Failed to exec install script
116 timing action:install Completed in 794ms
117 verbose unlock done using C:\Users\<user>\AppData\Roaming\npm-cache\_locks\staging-accbe1e340b579ac.lock for C:\Users\<user>\AppData\Local\vscode-sqltools\Data\node_modules\.staging
118 timing stage:rollbackFailedOptional Completed in 8849ms
119 timing stage:runTopLevelLifecycles Completed in 11502ms
120 silly saveTree Data
120 silly saveTree `-- @sap/hana-client@2.12.1-ms
120 silly saveTree   `-- debug@3.1.0
120 silly saveTree     `-- ms@2.0.0
121 warn enoent ENOENT: no such file or directory, open 'C:\Users\<user>\AppData\Local\vscode-sqltools\Data\package.json'
122 verbose enoent This is related to npm not being able to find a file.
123 warn Data No description
124 warn Data No repository field.
125 warn Data No README data
126 warn Data No license field.
127 verbose stack Error: @sap/hana-client@2.12.1-ms install: `node checkbuild.js`
127 verbose stack Exit status 3221226356
127 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
127 verbose stack     at EventEmitter.emit (events.js:315:20)
127 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
127 verbose stack     at ChildProcess.emit (events.js:315:20)
127 verbose stack     at maybeClose (internal/child_process.js:1048:16)
127 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
128 verbose pkgid @sap/hana-client@2.12.1-ms
129 verbose cwd C:\Users\<user>\AppData\Local\vscode-sqltools\Data
130 verbose Windows_NT 10.0.19042
131 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "@sap/hana-client"
132 verbose node v14.16.1
133 verbose npm  v6.14.12
134 error code ELIFECYCLE
135 error errno 3221226356
136 error @sap/hana-client@2.12.1-ms install: `node checkbuild.js`
136 error Exit status 3221226356
137 error Failed at the @sap/hana-client@2.12.1-ms install script.
137 error This is probably not a problem with npm. There is likely additional logging output above.
138 verbose exit [ 3221226356, true ]

**Comment by larshp** [comment]
close? out of scope for this repository

**Comment by jeffalbion** [comment]
Yes, let's close it. @StefanButscher, feel free to e-mail myself if this is still an issue.

**Comment by brieucdesoutter** [comment]
Hi,

@jeffalbion Can you please re-open it ? I am having the same issue on Windows with @sap/hana-client@2.14.18 node@14.20.1 and npm@6.14.17

Thanks
