### ISSUE TITLE
hdb and hana-client comparison wrt CAP

### ISSUE THREAD

**Issue by DanSchlachter** [SAP/node-hdb#193]
Hello, 

as for CAP applications hdb is the preferred library over hana-client and default for new projects, would it be possible to reflect this as well in the readme here and change the following:

_When starting a new project, it is encouraged to use the fully featured @sap/hana-client driver_

**Comment by jeffalbion** [comment]
Hello,

While it's true hdb is the default driver for CAP applications, it's also true we do not recommend hdb for general usage in other projects. @sap/hana-client is the default for many other libraries used with other SAP npm libraries (@sap/xsjs, @sap/hdbext, @sap/hdi-deploy, etc.)

The statement above is alluding to the fact that our primary development focus for new and fully supported features is the @sap/hana-client and we would encourage its adoption where possible.

Best regards,
Jeff

**Comment by larshp** [comment]
note that the license for @sap/hana-client does not

> (d) permit mass data extraction from an SAP product to a non-SAP product
