### ISSUE TITLE
Multiple Container HDB

### ISSUE THREAD

**Issue by jazzmn** [SAP/node-hdb#22]
Hi there,

I should connect to a Multiple Container HDB.
Is it possible to connect with node-hdb?
(need to specify the name of the tenant database container in the connection options)

Thank you and best regards,
jazz

**Comment by holgerkoser** [comment]
For `node-hdb` to container name is just a schema name. The user needs to have privileges for this container. You can set the default schema with 
```sql
SET SCHEMA MY_CONTAINER;
```
