### ISSUE TITLE
Improve error handling for prepared statements and bulk insert

### ISSUE THREAD

**Issue by holgerkoser** [SAP/node-hdb#23]
The documentation, error handling and fault tolerance of prepared statements and bulk insert should be improved. 

See the following issues:
- [Bulk Insert: TypeError: value is out of bounds](#10) 
- [Weird error behaviour during batch update](#15)

**Comment by woverton** [comment]
FYI, you may be interested in the actual application I ran into this error making: https://www.npmjs.com/package/censql

**Comment by alexpenev-s** [comment]
Bulk Insert: TypeError: value is out of bounds - done
