### ISSUE TITLE
Date parsing - dates returned as strings

### ISSUE THREAD

**Issue by hagen** [SAP/node-hdb#24]
Column types DATE DATETIME, etc. are not returned as JavaScript Date objects, but as strings. Similar node libraries (pg, for example) return date type fields as JS dates.

lib/protocol/common/Reader.js, functions readDate, readTime, readTimestamp, etc. Perhaps to maintain backwards compat, conversion to a Date object could be optional, and specified when the client is initialise (clientOptions).

Cheers

**Comment by holgerkoser** [comment]
To return ISO Date Strings instead of Date Objects is an explicit decision and not bug. In many cases you just want to forward a resultSet to a UI via REST API. In this case you don't need a Javascript Date Object on the Server and you will end up in creating lots of unneeded object which will be serialized immediately. On the other hand creating Date Objects is much more expensive than creating Strings. A user of `hdb` can easily create Date Objects with the ISO String which are returned.
```js
new Date('2015-09-16T09:53:12Z')
```

**Comment by hagen** [comment]
Thanks for the reply Holger. I understand your point. In my case, and perhaps others, I'm not forwarding results to a UI, but performing some processing server-side on the result set. And for this, I need the data to be typed accordingly, whether it be string, int, float, or indeed, date. 

There are instances where I don't know the table/view definition being queried (e.g. dynamic queries, including JOINS), so the only indicator as to type is the resulting values themselves. The current implementation effectively makes it impossible to type check the results (for dates) without first parsing. Which is even more time consuming.

Perhaps a way around this, if you agree, would be to also return the schema/metadata in the exec callback, so that accurate type information for each column is available.

```javascript
client.exec(query, function(err, rows, meta) {
    // processing
}
````
My work around is to parse as accurately as possible, the first row of my result array, and apply the resulting types to all remaining values in the result set.

**Comment by holgerkoser** [comment]
I will add an option `rowsWithMetadata` which can be set on the client or passed as second argument in exec. If this is specified the rows Array will have a `metadata` property containing the columnMetadata.

```js
client.exec(sql, {
  rowsWithMetadata: true
}, function(err, rows) {
    console.log(rows.metadata);
}
```
or
```js
client.set('rowsWithMetadata', true);
client.exec(sql, function(err, rows) {
    console.log(rows.metadata);
}
```

**Comment by holgerkoser** [comment]
By the way. It has been possible to check results for Dates (DataTypes).

```js
client.execute(sql, function (err, rs) {
  rs.fetch(function (err, rows) {
    console.log(rs.metadata, rows);
  });
});
```

**Comment by hagen** [comment]
Fantastic - thank you indeed for the lightening turn around. Yes, I noted the option for streaming results/result set, which is why I thought that same/similar option might be appropriate for direct queries also.
Vielen dank!

**Comment by bsrdjan** [comment]
If the date value is empty in the db, is it returned as a null or an empty stting? I am asking becauee in a server side processing scenario a client can read an empty date and process other fields, not the date, and return the untouched empty date to the db, in an update for example. Anything special to considet in such scenario or it should work?
