### ISSUE TITLE
Batch insert has side effects on input parameters

### ISSUE THREAD

**Issue by georgifarashev** [SAP/node-hdb#27]
When doing batch insert the input array with arguments is changed.

*Steps to reproduce*:
1) You have to have a database table in which you will insert.

For example: ```CREATE COLUMN TABLE "SOME_SCHEMA"."SOME_TABLE" ( "ID" INT CS_INT, "NAME" NVARCHAR(255) CS_STRING ) ```

2) Execute this code:
```js
var hdb = require('hdb');
var client = hdb.createClient({
  host: <host>,
  port: <port>,
  user: <user>,
  password: <password>
});
var params = [[1, 'a'], [2, 'b']];
client.connect(onConnect);

function onConnect(err) {
  console.log(JSON.stringify(params));
  client.prepare('INSERT INTO "SOME_SCHEMA"."SOME_TABLE" VALUES(?,?);', onPrepare);
}

function onPrepare(err, statement) {
  statement.exec(params, onExec);
}

function onExec(err, rows) {
  console.log(JSON.stringify(params));
}
```

*Expected result*:
`[[1,"a"],[2,"b"]]`
`[[1,"a"],[2,"b"]]`

*Actual result*:
`[[1,"a"],[2,"b"]]`
`[]`

*Problem*:
the params array is modified

**Comment by holgerkoser** [comment]
Currently the parameters are not copied. This should be changed in future versions, your are right. As a workaround you could do the following change:  
```diff
- statement.exec(params, onExec);
+ statement.exec(params.slice(), onExec);
```
to achieve the same result.
