### ISSUE TITLE
Error while opening tunnel

### ISSUE THREAD

**Issue by pallavik6** [SAP/node-hdb#30]
I had installed JDK version 1.8 initially but when I was trying to open tunnel using command neo open-db-tunnel... I got an error saying "Java cannot be found on your system". When I checked java -version it gave me error in registry key saying 1.7 is required. I installed JDK 1.7 & things went fine afterwards. But I would like to understand the current HCP SDK does not support 1.8 version or is there a new Java web file I should refer to.

Regards,
Pallavi

**Comment by holgerkoser** [comment]
This is not related to node-hdb.

Regards, Holger
