### ISSUE TITLE
LIMIT query runs really slow with node-hdb

### ISSUE THREAD

**Issue by abhikco** [SAP/node-hdb#31]
node-hdb version: 0.5.3
Running a SELECT query with LIMIT option using node-hdb is really slow.

Parent query: ```select * from TABLE where A=5 ORDER BY B;```

Total Number of Rows: 
```select count(*) from TABLE where A= 5``` , Output: ```1102```

Limit Query: ```select * from TABLE where A=5 order by B limit 200```

Code: 
```javascript
var d = new Date();
client.prepare("select * from TABLE where A=5 order by B limit 200", function(err, statement) {
                if (err) {
                    console.error('Error during query preparation: ', query, err);
                    return callback(err);
                }
                statement.exec(values, function(err, rows) {
                    console.log('Time taken for prepared query: %s seconds', (new Date() - d) / 1000);
                    if (err) {
                        console.error('Error during statement execution: ', query, err);
                        return callback(err);
                    }
                    return callback(err, rows);
                });
            });
```

Output of the code above: ```Time taken for prepared query: 53.291 seconds```

The same query runs just fine (465 ms) via HANA Studio.

P.S.: I changed the LIMIT query to ```SELECT * FROM
(select *, ROW_NUMBER() over (order by TID) as LID from TABLE where A=5)
WHERE LID <= 200```. This gives better performance (25 seconds) but nowhere near HANA Studio.

**Comment by holgerkoser** [comment]
All queries with LIMIT I have ever executed returned very fast. I am not able to reproduce this issue with the given description of the problem. However, there two undefined variables in the code example. One is `query` the other is `values`. I also do not understand why you use prepared statement without any parameters. You also do not describe which columns your table contains ... How should I help if you do not describe in details what are you doing.
 
What is the result if you do not prepare?
```js
console.time('no prepare');
client.exec("select * from TABLE where A=5 order by B limit 200", function(err, rows) {
  console.timeEnd('no prepare');
});
``` 

What is the result if you only select A?
```js
console.time('select A');
client.exec("select A from TABLE where A=5 order by B limit 200", function(err, rows) {
  console.timeEnd('select A');
});
``` 

What is the result if you do not auto fetch complete rows?
```js
console.time('no autoFetch');
client.execute("select * from TABLE where A=5 order by B limit 200", function(err, rs) {
  console.timeEnd('no autoFetch');
});
```

**Comment by abhikco** [comment]
Hello Holger,
I should've closed this issue earlier and apologies for providing incomplete information. I should've mentioned that one of the columns in the table was of type NCLOB and I was auto-fetching all rows, instead of using a resultSet. Using a result set and some streaming logic, the fetch times are manageable now.

I am closing this. Thank you for your help and apologies once again.

Best Regards, Abhi
