### ISSUE TITLE
Setting active schema

### ISSUE THREAD

**Issue by woverton** [SAP/node-hdb#35]
Hi there,

I am wondering if there is a way to set the current active schema so that it does not need to be specified every query. Thanks.

P.s. is there a better place to ask this question?

**Comment by dotchev** [comment]
@woverton, you can set the current schema via SQL
```sql
SET SCHEMA <schema_name>
```
See [SAP HANA SQL Reference](https://help.sap.com/saphelp_hanaplatform/helpdata/en/20/fd550375191014b886a338afb4cd5f/content.htm)

**Comment by woverton** [comment]
I didn't realise it would be that simple! I expected it to be like other db libraries where schema is a connection argument.

Thank you very much!
