### ISSUE TITLE
Unicode support for select statements?

### ISSUE THREAD

**Issue by gbarrett1988** [SAP/node-hdb#36]
I'm having issues displaying unicode characters using node-hdb select queries. The first attached image shows the unicode character correctly stored in the HDB (screenshot from HANA Admin console).
![hdb](https://cloud.githubusercontent.com/assets/17708487/14321757/841e1f04-fbe8-11e5-9cd6-396e6f6fd2c2.PNG)

The second image shows my webstorm console after retrieving the same piece of data with the out of bounds placeholder for unicode characters.
![node-hdb](https://cloud.githubusercontent.com/assets/17708487/14321758/841e3606-fbe8-11e5-92e0-20bccea08fe6.png)

Are there any workarounds for this behavior?

**Comment by woverton** [comment]
What else are you doing in your application? I can display non unicode characters just fine.

Is it possible that your terminal is using a non unicode font perhaps?

![image](https://cloud.githubusercontent.com/assets/9078302/14322823/170de16e-fc16-11e5-8e5e-420a74cf6da4.png)

**Comment by woverton** [comment]
As you mention you are using webstorm, please try this: http://stackoverflow.com/questions/1082343/unicode-characters-appear-as-question-marks-in-intellij-idea-console

**Comment by gbarrett1988** [comment]
I tested webstorm it displays the unicode characters fine. The application exhibiting this issue is running on a linux server using a simple node command to run, so it's not related to webstorm at all.

Additionally, the application is displaying the output in BentonSans Light which does support unicode.

We're simply using to reproduce this issue:
```
db.exec(query, function(err,data){
console.log(data);
});
```

**Comment by woverton** [comment]
In my console that exact code works fine. Do you think you could try another terminal besides your webstorm one just to be sure?

**Comment by gbarrett1988** [comment]
I ran the code outside of webstorm in a Git Bash terminal.
![image](https://cloud.githubusercontent.com/assets/17708487/14323550/f5ce3598-fbee-11e5-96b4-838749c01770.png)

The production code runs on a linux server and doesn't use webstorm. So I really don't think it's related.

**Comment by woverton** [comment]
If you run the query in hana studio and export it to a csv can you then read the the csv via a terminal application and see the character correctly?

The source of the data (linux or not linux server) would not be the issue, the thing which reads the data would be the issue.

**Comment by woverton** [comment]
Could you verify that you have putty set up for utf8 support? (If you're using putty)

http://thegreyblog.blogspot.co.uk/2009/08/configuring-putty-to-use-utf-8.html

**Comment by gbarrett1988** [comment]
I'm not using putty. The export from HANA Admin console does not have the issue.

**Comment by gbarrett1988** [comment]
Here's my code that I'm using to test the issue

```
var hdb = require('hdb');

var myDB= {
    host : 'myHanaDB',
    port : myPort,
    user : 'myUser',
    password : 'myPassword',
};

var db = hdb.createClient(myDB);

var query = "select city from myDb.myTable where city like 'Le V%'";

db.connect(function(err){
    if (err){
        console.warn(err);
        return;
    }
    db.exec(query, function(err, data){
        if (err){
            console.warn(err);
            return;
        }
        // expected output: Le Vésinet
        // actual output: Le V�sinet
        console.log(data);
    });
});
```

**Comment by woverton** [comment]
I just can't replicate this Im afraid.

The last thing I can say is try the exact program I am using: https://www.npmjs.com/package/censql

If that returns the same problem it is 100% not related to the library.

```
> SELECT 'Le Vésinet' AS NAME FROM DUMMY
┌────────────┐
│ NAME       │
├────────────┤
│ Le Vésinet │
└────────────┘
```

**Comment by gbarrett1988** [comment]
Hmmm yeah I was able to reproduce it with this CLI.
![image](https://cloud.githubusercontent.com/assets/17708487/14351832/7ccddda4-fc9f-11e5-95f6-4a169e415215.png)

But when I selected from dummy I did not receive the issue
![image](https://cloud.githubusercontent.com/assets/17708487/14352381/38b51652-fca2-11e5-827c-2bf55db3ba48.png)

I doubt it's a mis-configuration of the hana db otherwise the admin console would show the same issue. Just seems to be a transport issue between the server and node-hdb and now censql.

Can you try creating a database with that entry and pulling it down remotely to replicate the issue? The column datatype for city is a VARCHAR 512

**Comment by woverton** [comment]
Oh I see. I've not ran into this before, I shall do as you suggest and let you know if I find anything tomorrow. it might be worth trying an NVARCHAR in the meantime.

**Comment by gbarrett1988** [comment]
I thought the same thing, but I didn't see an option for NVARCHAR in hana. I guess it's not quite typical SQL, but I'm pretty new to hana so I'll tinker around with it as well.

**Comment by woverton** [comment]
It is certainly available in HANA, check this out: https://help.sap.com/saphelp_hanaplatform/helpdata/en/20/a1569875191014b507cf392724b7eb/content.htm

**Comment by gbarrett1988** [comment]
Hi William, I don't know if this helps unravel the mystery at all but I found this code on stackoverflow which converts hex as a string into a human readable string:
```
function hex2a(hexx) {
    var hex = hexx.toString();//force conversion
    var str = '';
    for (var i = 0; i < hex.length; i += 2)
      str += String.fromCharCode(parseInt(hex.substr(i, 2), 16));
    return str;
  }
```

I inserted the following code for debugging to hdb/lib/protocol/ResultSet.js line: 316
```
    console.warn('default[utf8]: %s', data.buffer.toString());
    console.warn('-----');
    console.warn('ascii: %s', data.buffer.toString('ascii'));
    console.warn('-----');
    var hex = data.buffer.toString('hex');
    console.warn('hex code in buffer: %s', hex);
    console.warn('hex2a fn result: %s', hex2a(hex));
```

Which turned up some pretty interesting results:
![image](https://cloud.githubusercontent.com/assets/17708487/14355410/c764175c-fcae-11e5-8dbd-542bdd970796.png)

The only thing I can muster is that Node.js Buffer.toString command does not work properly and that seems to be what node-hdb is using to process the hex buffer for inbound data. I'll update again if I find more. But it might be worth having the EventEmitter callback that's handling on('data', callback) implement an alternative to the buffer.toString method.

**Comment by woverton** [comment]
Playing CenSQL:
![image](https://cloud.githubusercontent.com/assets/9078302/14356241/ef1fea5a-fcdb-11e5-810d-c8a6dccac0ec.png)

----

I am still unable to replicate this. Can you please let me know what you're using?
- OS
- terminal program
- terminal type ```($ echo $TERM)```
- editor
- Hana Version
- Nodejs version ```($ node --version)```

**Comment by gbarrett1988** [comment]
Yeah that was the issue. For whatever reason HANA/DB will store unicode even if it is VARCHAR and the admin console will even handle it correctly. But semantically it really should be an NVARCHAR and not work. I'll perform the update later today thanks for looking into this.

**Comment by woverton** [comment]
Good stuff :+1: 

(Please make sure to close the issue)
