### ISSUE TITLE
Support LOBs as string feature.

### ISSUE THREAD

**Issue by gsamal** [SAP/node-hdb#39]
I am getting Buffer as result for LOB data. I found out all LOB objects are getting converted to Buffer while retrieving result set. But I need the Large object as String in my feature. So, isn't there be an option to convert it to string again ?
*Optionally rolling through all result set in my side would consume a lot of time and a bad option.

**Comment by pratikargus** [comment]
I am facing this issue as well. Please fix this if possible.

**Comment by woverton** [comment]
Can you not use ```mybuffer.toString('utf8');```?

**Comment by woverton** [comment]
This is happening because LOBs are binary data, so not always strings. Therefore you have to convert your binary data into whatever format you would like it to be.

**Comment by gsamal** [comment]
@woverton I realized that later. You are right. But in my case its typical text. So I forked the repo and made that change to avoid extra looping on result set.

**Comment by woverton** [comment]
Okay, glad that's sorted!

Lastly, you could consider changing the column type in the database to something like TEXT in order to gain a performance advantage.
