### ISSUE TITLE
Configure a default schema in connection

### ISSUE THREAD

**Issue by gsamal** [SAP/node-hdb#42]
Hi, I am trying to use a schema other than "SYSTEM" to use as my default schema, so that I don't have to add schema name in every query. But I don't find a way to do so. 
Any help will be really appreciated !

**Comment by woverton** [comment]
run 'SET SCHEMA "MY_SCHEMA"' before you run any other query, like with
any other connection :)

On 10/06/2016, Gautam Samal <notifications@github.com> wrote:
> Hi, I am trying to use a schema other than "SYSTEM" to use as my default
> schema, so that I don't have to add schema name in every query. But I don't
> find a way to do so.
> Any help will be really appreciated !
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/SAP/node-hdb/issues/42


-- 
Yours,
William Overton

Software Developer

Office: 0115 951 9666  |  Support DDI: 0800 142 2710  | Mb: ​07769207674

Address: Unit 2 Orchard Place, Nottingham Business Park, Nottingham, NG8 6PX

<http://centiq.co.uk/>

About Centiq – *Read more <https://centiq.co.uk/#about-centiq>*

-- 
*Centiq have now moved to a NEW HQ!*


*Our new address:*
Centiq Ltd
Unit 2 Orchard Place
Nottingham Business Park
Nottingham
NG8 6PX


Confidentiality: This e-mail and its attachments are intended for the above 
named only and may be confidential. If they have come to you in error you 
must take no action based on them, nor must you copy or show them to 
anyone, please reply to this e-mail and highlight the error.

Security Warning: Please note that this e-mail has been created in the 
knowledge that Internet e-mail is not a 100% secure communications medium. 
We advise that you understand and observe this lack of security when 
e-mailing us.

Viruses: Although we have taken steps to ensure that this e-mail and 
attachments are free from any virus, we advise that in keeping with good 
computing practice the recipient should ensure they are actually virus free.

Centiq Ltd
Registered in England with number 3593921.
Registered office: Unit 1, Charles Park, Charles Way, Cinderhill Road, 
Nottingham, NG6 8RF

**Comment by gsamal** [comment]
Thank you. That seems to work.
