### ISSUE TITLE
Local Temporary table is not accessible

### ISSUE THREAD

**Issue by lathmun** [SAP/node-hdb#54]
Hi,
When I create local temporary table  using node-hdb module by using query given below

CREATE LOCAL TEMPORARY COLUMN TABLE "#1231CD57A6569D15E10000000A600482" AS (SELECT 1 FROM  DUMMY) WITH DATA

I'm not able to access the table. While when I create Global temporary table I'm able to access.

NOTE: I'm using the same connection with which I create a table.

any help would be highly appreciated.

**Comment by alexpenev-s** [comment]
Hi, I cannot reproduce the issue:

  client.exec('CREATE LOCAL TEMPORARY COLUMN TABLE "#1231CD57A6569D15E10000000A600482" AS (SELECT 1 FROM DUMMY) WITH DATA', function (err) {
    client.exec('select * from "#1231CD57A6569D15E10000000A600482"', function (err, data) {
      console.log(data);
    })
  });


Returns:
[ { '1': 1 } ]
