### ISSUE TITLE
Number of affected rows is returned as undefined during batch insert

### ISSUE THREAD

**Issue by venkateshilango7** [SAP/node-hdb#65]
**Present Scenario**
Number of affected rows is returned as undefined during batch insert when some of rows have error.
But the correct records are inserted into the data base.

**Expected scenario**
Both the parameters should be filled on the function call back containing both the error and number of inserted rows

![image](https://cloud.githubusercontent.com/assets/9502407/20331222/031b44ce-ab72-11e6-9560-0af2eeda90d0.png)

**Comment by alexpenev-s** [comment]
Please try v0.11.0
