### ISSUE TITLE
Encoding problem?

### ISSUE THREAD

**Issue by drleidig** [SAP/node-hdb#67]
I have the following statement:

https://gist.githubusercontent.com/drleidig/47e5ad6cb28c581fdef73f953d68f783/raw/80bff2b5f54f6f1f94b9341b13dbc6a088824ff8/statement.sql

(you have to download it to see the utf-8 characters)

Testing the statement with node-hdb:

https://gist.githubusercontent.com/drleidig/a95b36ee8b90f884b0fb4964d4bbc32c/raw/d33b8c4a1105cbbeabb7fe3f3305786acc1c11b2/encoding.js

I get an SQL syntax error: incorrect syntax near ...

When I test the statement from the SQL console within the HANA studio everything is fine.
I assume something with the encoding is going wrong. 
Somewhere in the docs I found that HANA is using CESU-8 encoding, is similar to utf-8 but not the same. Maybe this could be the source of the error?

**Comment by AHaberl** [comment]
Same here with a similar statement...  @gvachkov

**Comment by alexpenev-s** [comment]
Is the issue fixed with the latest driver?

**Comment by alexpenev-s** [comment]
Please reopen if you encounter any other encoding issues with cesu-8.
