### ISSUE TITLE
Is there a way to get the affected rows as an array instead of the number of rows?

### ISSUE THREAD

**Issue by abhikco** [SAP/node-hdb#7]
Hi,

Instead of returning the number of affected rows for a DML statement execution, is it possible to get the rows as objects themselves? For example, if an UPDATE statement affects 5 rows, I would like to get the 5 rows as an array of JS objects, instead of having to fire an extra SELECT query.

Regards
Abhi

**Comment by abhikco** [comment]
The same is valid for an INSERT statement as well. For example, if the column table in HANA has the primary key generated via IDENTITY or a sequence, I would want to get the row more than the number of rows affected. 

-Abhi

**Comment by holgerkoser** [comment]
In the SAP HANA SQL command network protocol it is defined that a DML statement returns the number of affected rows and not the row itself. Therefore also the hdb module behave like this. You have to SELECT the rows in a separate statement if you need them.

Best regards, Holger

**Comment by abhikco** [comment]
Hi Holger,
That's true and it is quite rightly so that the node-hdb module also behaves as such.
However, this leads me to think whether there are any plans to build an object-relational mapping tool for HANA based on Javascript. It would certainly be helpful for such issues.

Best Regards, Abhi

**Comment by holgerkoser** [comment]
Hi Abhi,

there are no plans from my side to build an object-relational mapping tool for SAP HANA. But it is of course possible to build for an adapter for e.g [Sequelize](http://sequelizejs.com/) or [Knex](http://knexjs.org/) like people already have done for 
*  [Loopback](https://www.npmjs.com/package/loopback-connector-saphana)
*  [Seneca](https://www.npmjs.com/package/seneca-hana-store)
*  [KidoZen Enterprise API's](https://www.npmjs.com/package/node-hana-api)

But there will be no ORM as part of hdb.

Best regards, Holger
