### ISSUE TITLE
Sends all queries in block letters

### ISSUE THREAD

**Issue by nikhil271995** [SAP/node-hdb#71]
invalid column name: INDEX_NAMES: line 1 col 38 (at pos 37). This error popus up even though a column name of index_names was existing. This worked on altering the table and changing the column name to block letters  . Any solution for this ?

**Comment by petar-iv** [comment]
Use double quotes around the column name in your SQL query.

Example:

1) Let's have a table defined like the following:
```sql
create schema "mixed_CASE_schema";
create table "mixed_CASE_schema"."mixed_CASE_table" ("case_sensitive_COLUMN" integer)
```

Note that the DB converts all names (schema names, table names, column names etc.) to upper case in case they are not surrounded with double quotes. This is valid for all kinds of queries.

2) Have the following JavaScript coding:
```js
  client.exec('INSERT INTO "mixed_CASE_schema"."mixed_CASE_table" (case_sensitive_COLUMN) VALUES (14)', function (err) {
    if (err) {
      return console.log('insert error:', err.message);
    }
    console.log('Insert successful');
  });
```

This will result in `insert error: invalid column name: CASE_SENSITIVE_COLUMN` - the same error you get. And as you can see the column name in the query does not have double quotes and the column name in the error message is all upper case.

3) Have the following JavaScript coding:
```js
  client.exec('INSERT INTO "mixed_CASE_schema"."mixed_CASE_table" ("case_sensitive_COLUMN") VALUES (14)', function (err) {
    if (err) {
      return console.log('insert error:', err.message);
    }
    console.log('Insert successful');
  });
```

The only difference here is the double quotes around "case_sensitive_COLUMN". The query is sucessfully executed and we get the `Insert successful` message.

Let me know if you still have issues.

**Comment by nikhil271995** [comment]
Worked for me (y). Thanks!
