### ISSUE TITLE
Connect to HCP HANA Trial

### ISSUE THREAD

**Issue by NilsFrkal** [SAP/node-hdb#76]
Hi Experts,

Is there a way to connect to the HCP trial account HANA database? We are running a nodejs application in a cloud foundary instance. We can't however figure out what the connection parameters will have to look like (specifically the hostname).

Thank you very much.

Best Nils

**Comment by surjikal** [comment]
Issue #1 might help.

**Comment by NilsFrkal** [comment]
Hi Nick. Thanks a lot for the fast response. I agree, issue #1 deals with the same question. However, it does not completely answer the question on how a nodejs application which runs on a cloud foundary instance can connect to the HANA database on HCP trial. Is the answer as simple as "this is currently not supported"? 

I would like to leave this issue open for a little while to see if there are any ideas. Otherwise I will be closing it soon.

Thanks again and best regards, Nils

**Comment by elango1s** [comment]
Hello Nils,
nodejs application in a cloud foundry is remote to the Hana DB that you are trying to connect.
There are two options as i understand:
1) Your case: connect to HANA Trial DB (a cloud instance) - don't think you can connect using DB connection parameters eg: hostname and port number. The option available is to open a database tunnel from your node js application. [This](https://help.hana.ondemand.com/help/frameset.htm?6930850a8f9a40489c01ed1aa381946d.html) may help.
2) Alternate case: Implement the node js cloud foundry application inside HANA XS Advanced (either on the same HANA trial instance you have or a standalone on-premise HANA express edition for free). - here HANA DB is local to the application and can connect by $.hdb.connection...

**Comment by NilsFrkal** [comment]
Hi Elango, thanks for your answer. I will close this issue now as it confirms my understanding. We are already using option 1 for the on-premise/AWS version of the application. Option 2 would require an extensive refactoring of the nodejs application, so this is not really doable. Best, Nils
