### ISSUE TITLE
Add the ability to cancel a statement

### ISSUE THREAD

**Issue by surjikal** [SAP/node-hdb#77]
It would be neat if the driver allowed you to cancel running queries.

It would allow my application to kill running queries when users close their browser, or if a query takes too long to execute. This would also allow my users to kill any long-running queries manually, (ex: using a cancel button on our UI). 

Perhaps the API could look something like:

```javascript
var query = client.exec("<statement>", function(err, result) {...});
query.cancel(doneCallback);
// or maybe...
var statementId = client.exec(...);
client.cancel(statementId, doneCallback);
```

This method could be added to the `ResultSet` class as well, or the `client.execute` call.

Any thoughts?

**Comment by woverton** [comment]
This may help: https://archive.sap.com/discussions/thread/2093315

**Comment by surjikal** [comment]
Nice, very helpful indeed!

What happens when a ResultSet is closed before all the rows have been fetched? This might be already implemented if it cancels the running query!

**Comment by alexpenev-s** [comment]
When the ResultSet is closed a CLOSERESULTSET message is sent to HANA, so the processing should stop.

**Comment by surjikal** [comment]
Exellent! That is great news. Thanks for the help!
