### ISSUE TITLE
Slow performance with insert statement

### ISSUE THREAD

**Issue by simoncht** [SAP/node-hdb#82]
Hi and thank you for this wonderful node.js npm. 

I was wondering if you could have be with a performance problem that I am facing when using this module. I have high incoming volume of data that i would like to insert into the table however, the insert statement is taking around 5-10 seconds to execute and in this instance. I am streaming data back from IOT and while i am waiting for the insert statement to execute, i am loosing other data. 

i am not sure if i have done this write but I would appreciate your help if you can hint what is wrong with the code below. 

```

try{		
	client.prepare('insert intot tblTable values (?, ?)', function(err, statement){
		  if (err) {
		    return console.error('Prepare error:', err);
		  }
		  statement.exec([[json.id, json.text]], function(err, affectedRows) {
		    if (err) {	
		      return console.error('Exec error:', err);
		    }
		    console.log('Array of affected rows:', affectedRows + '\n');
   		  });
		});

} catch(err){	
	console.log("missing user node")
};
```

**Comment by venkateshilango7** [comment]
Can you look at the possibilty of using batch execution
https://github.com/SAP/node-hdb/blob/master/examples/app9.js

**Comment by simoncht** [comment]
Hi Venkateshilango7, 

I did and both method did not improve the result. I am not sure if it is an issue with out HANA server or the the way i am using the code.

**Comment by alexpenev-s** [comment]
Hi, 
My understanding is that you have large volumes of data and you insert them as they become available. This is probably overloading the DB with a tons of separate insert statements. 
My suggestion is to buffer the incoming data into batches and insert them into HANA using bulk insert mentioned above. 
The idea would be to make less calls to HANA.

**Comment by pratiksanglikar** [comment]
I think using any of the queueing services like Amazon SQS would help too.
That way you would not lose the data points while your first data is being inserted.
