### ISSUE TITLE
How to connect VM in HCP with Hana db in HCP ?

### ISSUE THREAD

**Issue by Vigneshbosch** [SAP/node-hdb#86]
Hi, 

I have purchased a VM on HCP and executing a python code from VM to connect  HANA DB  on HCP. 

- Do we need to open the DB tunnel in VM Machine to establish connection with HANA ? 
- Can Neo sdk be used in VM to open the DB tunnel (Plz note : the VM is a Linux Machine) ?

Thanks 
Vignesh

**Comment by alexpenev-s** [comment]
Hi Vignesh, 
This is a nodejs driver for connecting to HANA. It's independent of platform and infra structure/network setup. 
Please contact the the seller on how to obtain proper support.
