### ISSUE TITLE
Bad credentials results in ECONNRESET

### ISSUE THREAD

**Issue by adhurst** [SAP/node-hdb#91]
Attempting to make a connection using incorrect credentials results in an ECONNRESET error.

Below is the output of the attached repro:
[client.zip](https://github.com/SAP/node-hdb/files/1122441/client.zip)

Connect error { [Error: authentication failed]
  message: 'authentication failed',
  code: 10,
  sqlState: '28000',
  level: 1,
  position: 0 }
Network connection error { Error: read ECONNRESET
    at exports._errnoException (util.js:1012:11)
    at TCP.onread (net.js:563:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

**Comment by alexpenev-s** [comment]
It looks like HANA is abruptly closing the connection. I suggest to take a look at the HANA logs to see what is happening.

**Comment by adhurst** [comment]
Nothing interesting could be found in the HANA logs, but rebooting the HANA instance seems to have solved the issue for now.
Thanks,
- Adam
