### ISSUE TITLE
How insert ST_POINT?

### ISSUE THREAD

**Issue by frangeris** [SAP/node-hdb#95]
Hi, I'm having some issues trying to insert coordenates inside `ST_POINT`, here is my  code:

```javascript
// first attempt
statement.exec([
  [
  ....
  `new ST_POINT ('POINT (${latitud} ${longitud})')`
  ]
], (err, rows) => {
// TypeError: value.copy is not a function, start using Buffer

// second attempt
statement.exec([
  [
  ....
  Buffer.from(`new ST_POINT ('POINT (${latitud} ${longitud})')`)
  ]
], (err, rows) => {
// Error: internal error: exception  1: no.1600401  (spatial/parser/WkbParser.cpp:54) Invalid WKB byte order (110) at position 0
```

Any advice? Thanks

**Comment by alexpenev-s** [comment]
Could you please try with the WKB format when inserting the ST_POINT. Have a look at https://www.npmjs.com/package/wkx - it might help with some of the serializing/parsing 

If you do a select on a ST_POINT – the buffer you receive, should be able to be used back to be inserted.

**Comment by alexpenev-s** [comment]
Did you have  luck with the package wkx?

**Comment by frangeris** [comment]
End up using a stored procedure `INSERT_LOCATION`
```javascript
client.prepare('CALL INSERT_LOCATION (?, ?, ?, ?, ?, ?, ?, ?, ?)', (err, statement) => {
```
