### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by KernelDev** [SAP/node-hdb#98]
Hello,

could you add jsdocs comments to you source code? Using the API is much more intuitive when it is commented.

Thank you in advance,

KernelDev

**Comment by dotchev** [comment]
Hi,

Would you like to contribute a PR?

Cheers,
Peter

**Comment by KernelDev** [comment]
Hello,

I would like to, but I don´t understand you code at all since their are no comments. The problem seems a bit recursiv.

Best regards,

KernelDev
