### ISSUE TITLE
Promise Example

### ISSUE THREAD

**Issue by KernelDev** [SAP/node-hdb#99]
Hello,

could you provide an example how to use this libary with promises. I get random disconnects when I try to do it myself.

Best regards,

KernelDev

**Comment by alexpenev-s** [comment]
Could you please post the examples where the disconnects occur.
Try to run it with the env variable: NODE_DEBUG=hdb
This should give you more details on what is happening with the connection.
Best regards

**Comment by KernelDev** [comment]
I will close this, because the problem solved itself. I was having problem with 2 async operations writing to the same socket at the same time which ended in a protocol parse error.
